# Generated by Django 5.2.5 on 2025-09-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorempresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedorpersona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
